# This workflow will do a clean install of node dependencies, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: Delopy webpack_sample_project

on:
  push:
    branches: [ master ]

jobs:
  build:  # 新建一个 build 的任务

    runs-on: ubuntu-latest  # 运行的系统

    steps:
    - name: checkout
      uses: actions/checkout@v2  # 将仓库内 master 分支内容下载到工作目录
      
    - name: Use Node.js 10.x  # 配置Node环境
      uses: actions/setup-node@v1
      with:
        node-version: 10.x
      
    - name: Setup env
      env:
        DEPLOY_PRIVATE_KEY: ${{secrets.DEPLOY_PRIVATE_KEY}}
      run: |
        mkdir -p ~/.ssh/
        echo "$DEPLOY_PRIVATE_KEY" | tr -d '\r' > ~/.ssh/id_rsa # 配置密钥
        chmod 600 ~/.ssh/id_rsa
        ssh-keyscan github.com >> ~/.ssh/known_hosts
        git config --global user.name 'linxiaoki'
        git config --global user.email 'linxiaoki.@foxmail.com'
        # 安装依赖
        npm install -g webpack-cli
        npm install
      
    - name: Deploy
      run: |
        # publish
         webpack --config ./webpack.production.config.js
         git add -A
         git commit -m 'update: push dist'
         git push origin master
